"""
build_state_summaries.py — Aggregate tract-level data into state-level summaries

Input:  public/data/tracts/state_{FIPS}.json (generated by fetch_tract_data.py)
Output: public/data/state_summaries.json

Usage:
    python scripts/build_state_summaries.py

This script reads every state tract file and computes per-state aggregates:
- Population-weighted approximate medians for income and home values
- Affordability distribution (% affordable, stretched, unaffordable)
- Average rates for cost burden, homeownership, and vacancy
- Top 3 most affordable and bottom 3 least affordable tracts
"""

import json
import os
import sys

# ─── CONFIG ───────────────────────────────────────────────────────
SCRIPTS_DIR = os.path.dirname(os.path.abspath(__file__))
TRACTS_DIR = os.path.join(SCRIPTS_DIR, "..", "public", "data", "tracts")
OUTPUT_PATH = os.path.join(SCRIPTS_DIR, "..", "public", "data", "state_summaries.json")

# All 51 state FIPS codes (50 states + DC)
STATE_FIPS_LIST = [
    "01", "02", "04", "05", "06", "08", "09", "10", "11", "12",
    "13", "15", "16", "17", "18", "19", "20", "21", "22", "23",
    "24", "25", "26", "27", "28", "29", "30", "31", "32", "33",
    "34", "35", "36", "37", "38", "39", "40", "41", "42", "44",
    "45", "46", "47", "48", "49", "50", "51", "53", "54", "55",
    "56",
]

# FIPS code to state name mapping
STATE_NAMES = {
    "01": "Alabama",        "02": "Alaska",         "04": "Arizona",
    "05": "Arkansas",       "06": "California",     "08": "Colorado",
    "09": "Connecticut",    "10": "Delaware",       "11": "District of Columbia",
    "12": "Florida",        "13": "Georgia",        "15": "Hawaii",
    "16": "Idaho",          "17": "Illinois",       "18": "Indiana",
    "19": "Iowa",           "20": "Kansas",         "21": "Kentucky",
    "22": "Louisiana",      "23": "Maine",          "24": "Maryland",
    "25": "Massachusetts",  "26": "Michigan",       "27": "Minnesota",
    "28": "Mississippi",    "29": "Missouri",       "30": "Montana",
    "31": "Nebraska",       "32": "Nevada",         "33": "New Hampshire",
    "34": "New Jersey",     "35": "New Mexico",     "36": "New York",
    "37": "North Carolina", "38": "North Dakota",   "39": "Ohio",
    "40": "Oklahoma",       "41": "Oregon",         "42": "Pennsylvania",
    "44": "Rhode Island",   "45": "South Carolina", "46": "South Dakota",
    "47": "Tennessee",      "48": "Texas",          "49": "Utah",
    "50": "Vermont",        "51": "Virginia",       "53": "Washington",
    "54": "West Virginia",  "55": "Wisconsin",      "56": "Wyoming",
}


# ─── HELPERS ──────────────────────────────────────────────────────

def weighted_median(values_weights):
    """
    Compute an approximate population-weighted median.

    values_weights: list of (value, weight) tuples.
    Sorts by value, walks through cumulative weight until reaching 50%.
    This gives a population-weighted median of tract-level medians.
    """
    if not values_weights:
        return None

    # Filter out None values and zero/negative weights
    valid = [(v, w) for v, w in values_weights if v is not None and w is not None and w > 0]
    if not valid:
        return None

    # Sort by value
    valid.sort(key=lambda x: x[0])

    total_weight = sum(w for _, w in valid)
    if total_weight <= 0:
        return None

    half = total_weight / 2.0
    cumulative = 0.0

    for value, weight in valid:
        cumulative += weight
        if cumulative >= half:
            return round(value)

    # Fallback: return the last value
    return round(valid[-1][0])


def safe_avg(values):
    """Compute average of a list, filtering out None values."""
    valid = [v for v in values if v is not None]
    if not valid:
        return None
    return round(sum(valid) / len(valid), 1)


def safe_pct(count, total):
    """Compute a percentage, returning None if total is zero."""
    if total is None or total <= 0:
        return None
    return round((count / total) * 100, 1)


def build_tract_summary(tract):
    """
    Build a compact summary dict for a single tract (used in top/bottom lists).
    Includes livability context fields alongside affordability.
    """
    return {
        "geoid": tract.get("geoid"),
        "name": tract.get("name"),
        "county_fips": tract.get("county_fips"),
        "population": tract.get("population"),
        "median_household_income": tract.get("median_household_income"),
        "median_home_value": tract.get("median_home_value"),
        "affordability_ratio": tract.get("affordability_ratio"),
        "affordability_gap": tract.get("affordability_gap"),
        "homeownership_rate": tract.get("homeownership_rate"),
        "vacancy_rate": tract.get("vacancy_rate"),
        "poverty_rate": tract.get("poverty_rate"),
        "unemployment_rate": tract.get("unemployment_rate"),
        "median_age": tract.get("median_age"),
    }


# ─── STATE PROCESSING ────────────────────────────────────────────

def process_state(state_fips):
    """
    Load the tract file for one state and compute aggregated summaries.

    Returns a summary dict for the state, or None if the file is missing.
    """
    state_name = STATE_NAMES.get(state_fips, f"Unknown ({state_fips})")
    tract_file = os.path.join(TRACTS_DIR, f"state_{state_fips}.json")

    if not os.path.exists(tract_file):
        print(f"  WARNING: {tract_file} not found, skipping {state_name}")
        return None

    with open(tract_file) as f:
        tracts = json.load(f)

    if not tracts:
        print(f"  WARNING: {tract_file} is empty, skipping {state_name}")
        return None

    # ─── Basic counts ─────────────────────────────────────────
    total_tracts = len(tracts)
    total_population = sum(t.get("population") or 0 for t in tracts)

    # ─── Population-weighted medians ──────────────────────────
    income_weights = [
        (t.get("median_household_income"), t.get("population"))
        for t in tracts
    ]
    home_value_weights = [
        (t.get("median_home_value"), t.get("population"))
        for t in tracts
    ]

    median_income = weighted_median(income_weights)
    median_home_value = weighted_median(home_value_weights)

    # ─── Affordability distribution ───────────────────────────
    # Only count tracts that have a valid affordability ratio
    tracts_with_ratio = [t for t in tracts if t.get("affordability_ratio") is not None]
    ratio_count = len(tracts_with_ratio)

    affordable_count = sum(
        1 for t in tracts_with_ratio if t["affordability_ratio"] <= 3
    )
    stretched_count = sum(
        1 for t in tracts_with_ratio if 3 < t["affordability_ratio"] <= 5
    )
    unaffordable_count = sum(
        1 for t in tracts_with_ratio if t["affordability_ratio"] > 5
    )

    pct_affordable = safe_pct(affordable_count, ratio_count)
    pct_stretched = safe_pct(stretched_count, ratio_count)
    pct_unaffordable = safe_pct(unaffordable_count, ratio_count)

    # ─── Average affordability ratio ──────────────────────────
    ratios = [t["affordability_ratio"] for t in tracts_with_ratio]
    avg_affordability_ratio = safe_avg(ratios)

    # ─── Average rates ────────────────────────────────────────
    avg_cost_burden_rate = safe_avg(
        [t.get("pct_cost_burdened_renters") for t in tracts]
    )
    avg_homeownership_rate = safe_avg(
        [t.get("homeownership_rate") for t in tracts]
    )
    avg_vacancy_rate = safe_avg(
        [t.get("vacancy_rate") for t in tracts]
    )

    # ─── Top 3 most affordable tracts (lowest ratio) ─────────
    # Filter for livability: require population >= 500 to avoid empty tracts
    livable_tracts = [
        t for t in tracts_with_ratio
        if (t.get("population") or 0) >= 500
    ]

    # Sort ascending for top (most affordable)
    sorted_asc = sorted(livable_tracts, key=lambda t: t["affordability_ratio"])
    top_3 = [build_tract_summary(t) for t in sorted_asc[:3]]

    # ─── Bottom 3 least affordable tracts (highest ratio) ────
    sorted_desc = sorted(livable_tracts, key=lambda t: t["affordability_ratio"], reverse=True)
    bottom_3 = [build_tract_summary(t) for t in sorted_desc[:3]]

    return {
        "state_fips": state_fips,
        "state_name": state_name,
        "total_tracts": total_tracts,
        "total_population": total_population,
        "median_income": median_income,
        "median_home_value": median_home_value,
        "avg_affordability_ratio": avg_affordability_ratio,
        "pct_affordable": pct_affordable,
        "pct_stretched": pct_stretched,
        "pct_unaffordable": pct_unaffordable,
        "avg_cost_burden_rate": avg_cost_burden_rate,
        "avg_homeownership_rate": avg_homeownership_rate,
        "avg_vacancy_rate": avg_vacancy_rate,
        "top_3_tracts": top_3,
        "bottom_3_tracts": bottom_3,
    }


# ─── MAIN ─────────────────────────────────────────────────────────

def main():
    print("=" * 60)
    print("Building State Summaries from Tract Data")
    print("=" * 60)
    print()
    print(f"Tract data directory: {TRACTS_DIR}")
    print(f"Output file:          {OUTPUT_PATH}")
    print()

    if not os.path.isdir(TRACTS_DIR):
        print(f"ERROR: Tract data directory not found: {TRACTS_DIR}")
        print("Run fetch_tract_data.py first to generate tract data files.")
        sys.exit(1)

    summaries = {}
    processed = 0
    skipped = 0

    for idx, fips in enumerate(STATE_FIPS_LIST, start=1):
        state_name = STATE_NAMES.get(fips, fips)
        print(f"[{idx}/{len(STATE_FIPS_LIST)}] {state_name}...", end=" ", flush=True)

        summary = process_state(fips)

        if summary is not None:
            summaries[fips] = summary
            processed += 1
            print(
                f"{summary['total_tracts']} tracts, "
                f"pop {summary['total_population']:,}, "
                f"ratio {summary['avg_affordability_ratio']}"
            )
        else:
            skipped += 1
            # Warning already printed by process_state

    # ─── Write output ─────────────────────────────────────────
    os.makedirs(os.path.dirname(OUTPUT_PATH), exist_ok=True)

    with open(OUTPUT_PATH, "w") as f:
        json.dump(summaries, f, indent=None, separators=(",", ":"))

    file_size_kb = os.path.getsize(OUTPUT_PATH) / 1024

    # ─── Summary ──────────────────────────────────────────────
    print()
    print("=" * 60)
    print(f"States processed: {processed}/{len(STATE_FIPS_LIST)}")
    if skipped:
        print(f"States skipped:   {skipped}")
    print(f"Output file:      {OUTPUT_PATH}")
    print(f"File size:        {file_size_kb:.1f} KB")

    # ─── National overview ────────────────────────────────────
    if summaries:
        all_tracts = sum(s["total_tracts"] for s in summaries.values())
        all_pop = sum(s["total_population"] for s in summaries.values())

        all_ratios = [
            s["avg_affordability_ratio"]
            for s in summaries.values()
            if s["avg_affordability_ratio"] is not None
        ]
        national_avg_ratio = round(sum(all_ratios) / len(all_ratios), 2) if all_ratios else None

        print()
        print("National Overview:")
        print(f"  Total tracts:             {all_tracts:,}")
        print(f"  Total population:         {all_pop:,}")
        print(f"  Avg affordability ratio:  {national_avg_ratio}")

        # Most and least affordable states
        states_by_ratio = sorted(
            [(s["state_name"], s["avg_affordability_ratio"])
             for s in summaries.values()
             if s["avg_affordability_ratio"] is not None],
            key=lambda x: x[1],
        )

        if states_by_ratio:
            print()
            print("  Most affordable states:")
            for name, ratio in states_by_ratio[:5]:
                print(f"    {name}: {ratio}")
            print()
            print("  Least affordable states:")
            for name, ratio in states_by_ratio[-5:]:
                print(f"    {name}: {ratio}")

    print()
    print("Done.")


if __name__ == "__main__":
    main()
