import type { CountyMetrics } from "./calculations";

// ─── REAL DATA (generated by scripts/build_app_data.js) ─────────
// Falls back to minimal mock data if the generated file doesn't exist.
import generatedData from "./generated-data.json";

// ─── TYPES ──────────────────────────────────────────────────────

export interface StateData {
  name: string;
  abbr: string;
  ratio: number;
  value: number;
  income: number;
}

interface TrendPoint {
  month: string;
  value: number;
  year: number;
  idx: number;
}

interface RatioPoint {
  month: string;
  ratio: number;
  idx: number;
}

interface CostBurdenPoint {
  name: string;
  value: number;
  color: string;
}

interface CountyRank {
  rank: number;
  county: string;
  state: string;
  income: number;
  value: number;
  ratio: number;
}

export interface KPISummary {
  nationalRatio: number;
  nationalMedianIncome: number;
  nationalMedianHomeValue: number;
  pctAffordable: number;
  totalCounties: number;
  avgCostBurdenedRenters: number;
  avgCostBurdenedOwners: number;
}

// ─── EXPORTS (same interface as before, now backed by real data) ─

export const STATES_DATA: StateData[] = generatedData.statesData as StateData[];

export const COST_BURDEN_DATA: CostBurdenPoint[] = generatedData.costBurdenData as CostBurdenPoint[];

export const TOP_AFFORDABLE: CountyRank[] = generatedData.topAffordable as CountyRank[];

export const LEAST_AFFORDABLE: CountyRank[] = generatedData.leastAffordable as CountyRank[];

export const KPI_SUMMARY: KPISummary = generatedData.kpiSummary as KPISummary;

export function generateNationalTrend(): TrendPoint[] {
  return generatedData.nationalTrend as TrendPoint[];
}

export function generateAffordabilityTrend(): RatioPoint[] {
  return generatedData.affordabilityTrend as RatioPoint[];
}

export function generateIncomeTrend() {
  // Derive from affordability trend + national trend
  const national = generatedData.nationalTrend as TrendPoint[];
  const ratios = generatedData.affordabilityTrend as RatioPoint[];
  return national.map((d, i) => ({
    month: d.month,
    income: ratios[i]?.ratio ? Math.round(d.value / ratios[i].ratio) : 0,
    idx: i,
  }));
}

export function getScatterData() {
  const westStates = ["CA", "HI", "WA", "OR", "NV", "AZ", "UT", "CO", "ID", "MT", "WY", "NM", "AK"];
  const neStates = ["NY", "MA", "NJ", "CT", "PA", "MD", "VA", "VT", "NH", "ME", "RI", "DE", "DC"];
  const southStates = ["TX", "FL", "GA", "NC", "TN", "AR", "MS", "OK", "WV", "SC", "AL", "LA", "KY"];

  return STATES_DATA.map((s) => ({
    ...s,
    pop: Math.round((Math.abs(Math.sin(s.ratio * 7)) * 30 + 2) * 1000000),
    region: westStates.includes(s.abbr)
      ? "West"
      : neStates.includes(s.abbr)
        ? "Northeast"
        : southStates.includes(s.abbr)
          ? "South"
          : "Midwest",
  }));
}

// ─── US STATES SVG PATHS (unchanged — static geometry) ──────────
export const US_STATES_SVG: Record<string, { d: string }> = {
  WA: { d: "M62,18L78,14L84,18L86,36L78,38L62,34Z" },
  OR: { d: "M56,38L82,36L86,56L76,64L54,58Z" },
  CA: { d: "M52,60L76,64L80,90L72,118L48,114L44,80Z" },
  NV: { d: "M76,64L86,56L92,72L84,98L72,96Z" },
  ID: { d: "M84,18L92,16L98,26L96,52L86,56L84,36Z" },
  MT: { d: "M92,16L130,12L132,34L96,38Z" },
  UT: { d: "M86,56L96,52L98,58L96,82L84,80L82,72Z" },
  AZ: { d: "M72,96L84,98L86,118L74,126L60,120Z" },
  CO: { d: "M98,58L126,56L128,78L100,80Z" },
  WY: { d: "M96,38L132,34L130,56L98,58Z" },
  NM: { d: "M86,100L100,98L102,128L84,130L76,126Z" },
  ND: { d: "M132,12L164,12L164,30L132,30Z" },
  SD: { d: "M132,30L164,30L164,48L132,48Z" },
  NE: { d: "M126,48L164,48L166,62L128,64Z" },
  KS: { d: "M128,64L166,62L168,80L130,82Z" },
  OK: { d: "M130,82L168,80L172,88L160,98L130,96Z" },
  TX: { d: "M120,98L160,98L172,100L168,140L142,152L112,142L108,118Z" },
  MN: { d: "M164,12L192,14L192,38L164,38Z" },
  IA: { d: "M166,38L192,38L194,56L168,56Z" },
  MO: { d: "M168,58L196,56L200,78L176,84L170,80Z" },
  AR: { d: "M176,84L200,80L202,100L178,102Z" },
  LA: { d: "M178,102L202,100L208,118L192,126L180,120Z" },
  WI: { d: "M192,14L214,16L216,38L194,38Z" },
  IL: { d: "M196,40L216,38L218,66L200,70L198,56Z" },
  MS: { d: "M202,100L214,98L218,126L208,128L204,118Z" },
  MI: { d: "M216,12L234,14L232,36L216,34Z" },
  IN: { d: "M218,40L232,38L234,62L220,64Z" },
  OH: { d: "M234,36L252,34L254,56L236,58Z" },
  KY: { d: "M220,66L254,58L258,72L228,76L222,74Z" },
  TN: { d: "M218,78L260,72L262,84L222,86Z" },
  AL: { d: "M218,88L236,86L240,114L222,116Z" },
  GA: { d: "M238,86L258,84L262,112L244,116Z" },
  FL: { d: "M240,116L268,112L278,130L266,152L250,140L242,126Z" },
  SC: { d: "M258,82L272,78L270,96L252,96Z" },
  NC: { d: "M252,72L280,68L282,78L256,82Z" },
  VA: { d: "M256,60L282,56L284,68L262,72Z" },
  WV: { d: "M254,52L264,50L266,62L256,66Z" },
  PA: { d: "M252,34L282,30L284,44L256,46Z" },
  NY: { d: "M264,16L290,12L288,32L262,34Z" },
  VT: { d: "M284,10L290,8L292,20L286,22Z" },
  NH: { d: "M290,8L296,8L294,22L290,20Z" },
  ME: { d: "M296,4L306,2L304,20L294,18Z" },
  MA: { d: "M288,26L302,24L302,30L290,30Z" },
  CT: { d: "M288,32L298,30L298,36L290,36Z" },
  NJ: { d: "M282,34L290,32L290,46L284,44Z" },
  DE: { d: "M282,44L288,44L288,50L284,50Z" },
  MD: { d: "M272,48L286,46L288,54L274,56Z" },
};

// ─── COUNTY LOOKUP (real data from ETL) ─────────────────────────
// Returns real county data from the full counties_acs.json loaded at build time.
// For client pages, use the API route or fetch from /data/counties_acs.json instead.
export function getMockCountyData(fips: string): CountyMetrics | null {
  // This function is used by server-rendered pages (area/[fips]).
  // For client components, fetch /data/counties_acs.json at runtime.
  return null;
}
